# GitHub Pages configuration
exclude:
  - ml/
  - server.py
  - README.md
  - LICENSE
  - logs/

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: "Deep Space Weather Model"
description: "Long-Range Solar Flare Prediction from Multi-Wavelength Images"

# Enable client-side routing support
include:
  - _redirects

# Markdown settings
markdown: kramdown
highlighter: rouge

# Sass/CSS settings
sass:
  sass_dir: web/css
  style: compressed 
